project 'UberClone.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UberClone' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UberClone
  pod 'Firebase/Core', '3.16.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Database', '3.16.0'
  pod 'Firebase/AdMob', '3.16.0'
  
end
