project 'PushNotifications.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PushNotifications' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PushNotifications
  pod 'Firebase/Core', '3.16.0'
  pod 'Firebase/Messaging'
end
